language: android
jdk: oraclejdk8
android:
    components:
        - platform-tools
        - tools
        - build-tools-24.0.0
        - android-24
        - sys-img-armeabi-v7a-android-22
        - sys-img-x86-android-17
        - extra-android-support
        - extra-android-m2repository
before_install:
    - chmod +x gradlew
env:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"